spring.application.name=authguard
server.port=8080

# Mesmos dados colocados no docker-compose.yml
spring.datasource.url=jdbc:postgresql://localhost:5432/authguard_db
spring.datasource.username=admin
spring.datasource.password=adminpassword

# Qual driver usar para conectar
spring.datasource.driver-class-name=org.postgresql.Driver

# Atualiza ou cria as tabelas no banco de dados, se não existirem
spring.jpa.hibernate.ddl-auto=update
# Exibe no terminal as queries SQL que o Hibernate está gerando por baixo dos panos
spring.jpa.show-sql=true
# Formata o SQL no terminal para ficar mais fácil de ler.
spring.jpa.properties.hibernate.format_sql=true

# CONEXÃO COM O REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379